bin/lib/Logos/Class.pm, bin/lib/Logos/Generator/Base/Class.pm, bin/lib/Logos/Generator/Base/Property.pm, bin/lib/Logos/Property.pm, bin/logos.pl
I've added a %property directive to Logos. It follows the same syntax as the @property directive.
It creates a fast way to emulate ivars in hooked classes. It adds getter and setter methods, which use Objective-C associated objects as the backend. It only supports Objective-C objects at the moment, but it may be possible to store C types.
Supports the following property attributes:
assign
retain
copy
nonatomic
getter
The 'setter' attribute will be implemented soon.
Consider merging my additions?
=> Add %property (logo?).

bin/lib/Logos/Class.pm, bin/lib/Logos/Generator/Base/Property.pm, bin/logos.pl
Fixes an issue where `%property` getters & setters were removed by Clang's optimizer if the property was never accessed.
No
`%property` is awesome, we should keep improving it.
**Operating System:** OS X 10.11
**Platform:** Uh...
**Target Platform:** iOS
**Toolchain Version:** Apple LLVM 7.0.2
**SDK Version:** iOS 9.2
=> [Logos] Generate getters & setters for %property even if it is never accessed

makefiles/package.mk
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
To avoid pincrush `could not open` error.
No
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
```
find /Users/hyde/dev/sleipnizer/.theos/_ -name \*.png -exec pincrush -i {} \;
/Users/hyde/dev/sleipnizer/.theos/_/Applications/MobileSafari.app/SleipnizerSettings.png: Error: could not open.
/Users/hyde/dev/sleipnizer/.theos/_/Applications/MobileSafari.app/ …
```
=> [package] Exclude symbolic file for pincrush target.

bin/lib/Logos/Generator/Base/Function.pm, bin/lib/Logos/Generator/MobileSubstrate/Function.pm, bin/logos.pl
Adds support for `%hookf` such that if the given function name is surrounded with `"` the function is dynamically looked up with `MSFindSymbol`. This helps ease writing hooks for mangled functions.
No
-
…
**Operating System:** iOS
**Platform:** iOS
**Target Platform:** All
**Toolchain Version:** N/A
**SDK Version:** N/A
=> [logos] Add support for dynamic lookup of functions in %hookf.

bin/logos.pl
Improves `%property` parsing of type and name.
Fixes issue #226.
[Test results](https://ghostbin.com/paste/w5gs6)
…
**Operating System:** iOS 6.1.4
**Platform:** iOS 6.1.4
**Target Platform:** iOS 6.1.4
**Toolchain Version:** Latest available
**SDK Version:** 8.1
=> [Logos] Fix %property parsing of type and name.

makefiles/targets/Linux/iphone.mk
Removes the need to have prefixes, such as `armv7-apple-darwin-` and `arm64-apple-darwin-` for the linux toolchains. With this change it should make sbingner's arm64e linux toolchain ([https://github.com/sbingner/llvm-project/releases/tag/v10.0.0-1](https://github.com/sbingner/llvm-project/releases/tag/v10.0.0-1)) "plug and play".
#482 
This is going to break backwards compatibility with old and current Kabir's linux toolchain which has those prefixes.
**Operating System:**
- Windows 10 (Debian WSL)
- Debian …
=> Remove $(SDKTARGET)- prefix name requirement for linux toolchain binaries

makefiles/instance/rules.mk
Added the `_THEOS_OBJ_FILE_TAG` to files generated by `generate-output-file-map.swift`.
#524.
Nope.
**Operating System:** macOS 11.0
**SDK Version:** iOS 13.5
=> Fixed #524

makefiles/instance/xcodeproj.mk
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
This PR allows lldb to correctly symbolicate xcodeproj-based binaries while debugging. This is achieved by making Xcode not strip DWARF info during debug builds, bringing it closer to how Theos normally behaves. It's usually alright for Xcode to strip this info during installation because it retains an un-stripped copy on the host, which lldb can refer to during symbolication. Since we provide a custom `derivedDataPath` while building, however, lldb is unable to locate the unstripped copy as it doesn't know about the custom path.
Does this …
=> Improve xcodeproj debugging

makefiles/master/aggregate.mk, makefiles/package.mk
Is there an approach to this other than just copy-pasting the content of internal-after-install? Or is this fine? My `make` skills aren't very sharp
=> `make uninstall` should unload target processes

makefiles/targets/Linux/iphone.mk
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
theos currently ignores `target=` commands for linux because it sets `-target arm64-apple-darwin` unconditionally after whatever the correct `-target` command is and no longer passes legacy flags
-----------------------------------------
Not that I know of
=> [Linux/iphone] Fix -target flag being overwritten

Prefix.pch
TargetConditionals.h needs to be included in Prefix.pch, otherwise TARGET_OS_IPHONE might not be defined which causes the later checks to fail.
Yes, #552 
See the issue for more information
No
**Operating System:** macOS 11.4
**Platform:** macOS
**Target Platform:** iOS
**Toolchain Version:** Xcode 12.5
**SDK Version:** iPhoneOS13.0
=> Fix TARGET_OS_IPHONE not being defined in Prefix.pch (Resolves #552)

Prefix.pch
Adresses concerns about my previous PR #596 (see comments)
No
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
No
**Operating System:** macOS
**Platform:** macOS
**Target Platform:** iOS
**Toolchain Version:** Xcode 12.5
**SDK Version:** iPhoneOS13.0
=> Prefix.pch: Don't import TargetConditionals.h unless neccessary, correctly undefine _THEOS_IS_SIMULATOR

makefiles/instance/rules.mk
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
xmi should be treated as objc++ rather than objc
…
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
Before this commit:
```
1.xmi:1:9: fatal error: 'string' file not found
#import <string>
```
After:
no error
…
**Operating System:** macOS Catalina 10.15.5 …
=> [rules] xmi should be treated as objc++ rather than objc

bin/install.exec
Adds compatibility with BSD su, which macOS and Procursus both take advantage of. Continues to work on Linux su.
=> Fix `install.exec` locally for iOS/macOS

.gitmodules
Without this, `git submodule update --init --recursive` fails with `fatal: not a git repository: ../../.git/modules/vendor/orion`
=> Fix orion git submodule url

bin/install-theos
I have just fixed a wrong url in the installer. When trying to install theos on iOS 12+ it askes if you have https://apt.procursus.us repo in on your package manager. I have changed it to ask for https://apt.procurs.us which is the correct url.
=> Fix procursus repo url on darwin-mobile

bin/install-theos
- Simplifies CI check
- Adjusts /opt owner var check for iOS (now case-sensitive)
- Standardizes "SDKs" capitalization
- Fleshes out the Xcode check on OSX -- will now check for CommandLineTools and either prompt to install Xcode or switch the DEVELOPER_DIR to it if it's installed (**UNTESTED**)
- Adjusts the WSL kernel check regex to correctly match both uppercase and lowercase "Microsoft"
- Updates the non-swift toolchain 
- Changes from the current non-swift toolchain (whose changes were cherry-picked into the new build):
- Added 32-bit arm support
- Updated ldid 
- Fixed ldid WSL v1 support
- Shrank size
- Bumped stable base (now LLVM-11)
- Cherry-picked NSString `format_arg` …
=> Installer update

bin/install-theos
See title
No
Ref: https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/
=> Fix shell profile ordering in installer

bin/install-theos
See title
I don't think so
- Currently will prompt for apt.bingner.com instead of procursus as the marker file check fails 
- File is now in prefixed path instead of root
- Untested 
=> Fix `install-theos` for rootless

bin/gen-commands.pl
I am not a pro in Perl. But `make commands` sometimes fails to generate a valid json if parallel building is enabled.
No
No, but I found clangd sometimes refused to load compile_commands.json due to syntax errors.
No
=> Add flock to gen-commands.pl to avoid race condition

makefiles/master/rules.mk
See title
I don't think so, no 
Improves upon 41007e9d2705a3fd38409b3f567339e189713aee
Previously, a failed SYSROOT check indicated to users that they did not have an SDK, but more often than not they had just specified an SDK that did not exist and thus the SYSROOT had been blanked.  
The current situation: 
- The Theos and Xcode SDK directories are checked in darwin_head.mk
- If both return blank (i.e., the user lacks SDKs), the build will fail w/ an error. 
- If not, the specified …
=> Adjust sysroot errors to better explain the issue at hand

bin/install-theos
The `dnf check-update` command in the installer lists the updatable packages and quits the script if there's any.
To fix it, at first I just changed it to `dnf update` which does update them, and it worked.
However, the Debian and Arch behaviours appear to be to "refresh the sources" as opposed to "update the system packages" (`apt update` vs `apt upgrade`, `pacman -Syy` vs `pacman -Syu`) and `dnf update` doesn't follow that intended behaviour.
To make sure the repositories are forcefully updated by dnf, the `--refresh` flag was added to the next line which installs some dependencies.
Closes #738.
Any …
=> [bin] remove dnf check-update during dependency install

bin/install-theos
See title
Resolves #736 
Was hesitant to do this because we need certain repos in order to install deps, but if those repos have issues the proceeding install cmds will error and that should suffice. Most of the time, update failures occur due to 3rd party repos that are not pertinent for theos' install.
=> Unconditionally proceed for repo updates

bin/install-theos
Switches sdk install to latest for each platform instead of all we provide
No
- Reliant on [theos/sdks#67](https://github.com/theos/sdks/pull/67)
- Someone on OSX please confirm that none of the flags used are GNU-specific
Linux (WSL)
=> Update `install-theos` for sdk releases

makefiles/instance/tweak.mk
For tweak projects, this PR allows the Substrate Filter Plist to be named `Filter.plist` as a reserved keyword, instead of forcing the plist to be named whatever `TWEAK_NAME` is. This is useful for an instance-based design - i.e. if developers wish to have a consistent file system layout across multiple projects. 
Note that this PR is in addition to TWEAK_NAME.pllist, not instead of. It will first try for TWEAK_NAME.plist. If available, great, and if not, it will fallback to trying Filter.plist. If that is available, great, and if not, it will throw an error. 
No …
=> Implement Filter.plist as a reserved keyword

makefiles/targets/Darwin/simulator.mk
Somehow, clang 15.0.0 and higher deprecates this flag on Apple Silicon but removes this flag on Intel platform. To fix the issue for both worlds, we just don't need this flag for clang 15.0.0 and higher. This doesn't affect the dylibs built for simulator and will still work fine.
…
…
…
=> Use `allow_simulator_linking_to_macosx_dylibs` linker flag only for clang <= 14.0.0

makefiles/instance/rules.mk
RIght now compilation for oldabi fails due to libroot only having a new ABI file.
Initially I tried using a patched lipo to combine both old ABI and new ABI slices into the same .a, this however does not work.
Now there are two .a files, one with an old ABI arm64e slice and one with a new one and we use the correct one based on the clang version being used when compiling.
Depends on https://github.com/theos/lib/pull/23 being merged first.
No
**Operating System:** macOS
**Target Platform:** iOS
=> Use oldabi libroot file when compiling with clang < 12.0.0

makefiles/instance/rules.mk
- Keeps single-arch projects single-arch thin bins
No
See convo with Daniel/Leptos in the Theos Discord (#theos-general)
Linux (WSL)
=> Only make FAT bin if TARGET_ARCHS > 1

bin/install-sdk, bin/install-theos
Adds script to quickly download an sdk from our sdk repo
No
Believe this was proposed at one point or another. I don't have a particular feeling toward having it or not having it, but figured I'd put something together for discussion 
Linux (WSL)
=> Add `install-sdk` script

bin/install-theos
- WSL can be identified by the "[Mm]icrosoft" substring in the kernel release
- Previously, this was checked via a lengthy two-part regex
- Part one worked as expected but part two, the release version, would work for v2 and not v1
- To remedy these, simpler checks are now used and the wsl v1 check was switched to a ! v2 check
No
Issue was brought to our attention through Discord
Linux (WSL -- v1 and v2) …
=> Simplify and fix WSL v1 check

makefiles/instance/rules.mk
- Removes any spaces from the TARGET_ARCHS when its count is == 1
- Ensures a valid UNIX path
Appears to resolve #808 
**before**
```
> Making all for tweak test…
==> Preprocessing Tweak.x…
==> Compiling Tweak.x (arm64)…
==> Linking tweak test (arm64)…
==> Generating debug symbols for test…
warning: no debug symbols in executable (-arch arm64)
cp: target '/home/lightmann/test/.theos/obj/debug/test.dylib.86a9eb47.unsigned': No such file or directory
```
**after**
```
> Making all for tweak test…
==> Preprocessing Tweak.x…
==> …
```
=> Ensure single-arch objs have spaces stripped before copying

bin/install-theos
Currently, running the install script on x86_64 and selecting the Swift toolchain fails.
This is caused by the request for the toolchain returning a 404.
No
Hotfix
=> Adjust Swift toolchain download URL for x86_64 (no arch suffix)

.github/workflows/offline-docs.yml, .github/workflows/update-submodules.yml
See title
No, but it will tick another item off of #308
Tested on [separate branch](https://github.com/L1ghtmann/theos/tree/my-docs) and worked like a charm. Would be nice if we could only run the workflow if theos/theos.dev is updated, but not sure that's possible. 
~~Edit: CSS looks to be borked atm~~
Linux (WSL)
=> Add workflow to add/update offline docs

makefiles/instance/rules.mk
this allows for creating a compile-commands.json for pure objective-c files aka .m files
which in turn allows for intellisense for these .m files
not that i am aware of
…
**Operating System:** Debian Bookworm 12
**Platform:** 
**Target Platform:** iphone/tweak
**Toolchain Version:** 13.0
**SDK Version:** iPhone 16.5
=> let `make commands` work for pure objective-c files

.github/workflows/offline-docs.yml
The current `offline-docs` workflow fails to push the changes because of repository settings.
See https://github.com/theos/theos/actions/runs/9532349020/job/26274358604#step:7:42
This PR uses the same token as the [`update-submodules`](https://github.com/theos/theos/blob/f40d18a6e6d83f18a17b604a3426fe3c1b3dd048/.github/workflows/update-submodules.yml#L15) to access the repo, which does work.
No
No.
I do not believe this change can be tested safely without pushing to `theos/theos:master`, …
=> Use UPDATE_SUBMODULES_TOKEN to push in offline-docs workflow

Prefix.pch
This PR fixes an error when compiling projects with `-pedantic` in `CFLAGS`.
The issue is that `import` is not supported in pedantic mode. To resolve this issue, this PR uses `include` instead of `import`. This is safe because the header being included uses a guard check to avoid being included multiple times: https://github.com/theos/sdks/blob/ca52092676249546f08657d4fc0c8beb26a80510/iPhoneOS16.5.sdk/usr/include/AvailabilityVersions.h#L24 
This is primary difference between `import` and `include`.
This PR only changes this one `import` in `Prefix.pch` because the rest of the file is deprecated.
Yes, …
=> Use include instead of import in Prefix.pch for improved compatibility

bin/install-sdk
This pull request reduces occuring of `1 - api.github.com request failed` error.
No.
[Yes](https://github.com/OwnGoalStudio/SingleMute/actions/runs/11795027751/job/32853960143).
See [Make authenticated requests](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#make-authenticated-requests).
The unauthenticated primary rate limit of GitHub API is **60 requests per hour**. That's not enough when you're using shared CI runners or …
=> Avoid rate limits of the GitHub APIs

bin/install-theos
The current script does not work on Fedora 41, so I have changed it to do so. The issues lies in trying to install the group by the name rather than the id, which is the (current) functionality. (See more at https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html)
No
```bash
Failed to resolve the transaction:
No match for argument: Development Tools
You can try to add to command line:
--skip-unavailable to skip unavailable packages
==> Dependency install command seems to have encountered an error. Please see the log …
```
=> Update Fedora Install Script

bin/install-theos
ZDOTDIR is the path to the user's zsh configuration, so it may not always be located in the home directory,
More information could be found in zsh man page,
No
No
No
=> Respect ZDOTDIR
